services:
    django:
        container_name: django
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: django
        volumes:
            - ./backend:/code
        ports:
            - "8002:8002"
        networks:
            - Inception

networks:
    Inception:
        name: inception
        driver: bridge