services:
    django:
        container_name: django
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: django
        volumes:
            - ./backend:/code
        ports:
            - "8002:8002"
        networks:
            - Inception
        depends_on:
            - postgres

    postgres:
        container_name: postgres
        build:
            context: ./postgres
            dockerfile: Dockerfile
        image: postgres
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - Inception
        environment:
            POSTGRES_USER: "anaraujo"            
            POSTGRES_PASSWORD: "1234"

    pgadmin4:
        container_name: pgadmin4
        image: pgadmin4
        build:
            context: ./pgadmin
            dockerfile: Dockerfile
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@email.com"
            PGADMIN_DEFAULT_PASSWORD: "1234"
            PGADMIN_LISTEN_PORT: "8080"
        networks:
            - Inception
        ports:
            - "8080:8080"
        depends_on:
            - postgres

networks:
    Inception:
        name: inception
        driver: bridge

