services:
    django:
        container_name: django
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: django
        volumes:
            - /home/anaraujo/Desktop/42_transcendence/backend:/code
        ports:
            - "8002:8002"
        networks:
            - Inception

networks:
    Inception:
        name: inception
        driver: bridge

volumes:
  django:
    name: django
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/anaraujo/Desktop/42_transcendence/backend'
