services:
    django:
        container_name: django-container
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: django
        volumes:
            - ./backend:/code
        ports:
            - "8002:8002"
        networks:
            - Transcendence
        depends_on:
            - postgres
            - redis

    postgres:
        container_name: postgres-container
        build:
            context: ./postgres
            dockerfile: Dockerfile
        image: postgres
        volumes:
            - ./data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - Transcendence
        env_file:
            - .env

    pgadmin4:
        container_name: pgadmin4-container
        image: pgadmin4
        build:
            context: ./pgadmin
            dockerfile: Dockerfile
        restart: always
        env_file:
            - .env
        networks:
            - Transcendence
        ports:
            - "8080:8080"
        depends_on:
            - postgres

    redis:
        container_name: redis-container
        image: redis
        build:
            context: ./redis
            dockerfile: Dockerfile
        restart: always
        networks:
            - Transcendence
        ports:
            - "6379:6379"

networks:
    Transcendence:
        name: Transcendence
        driver: bridge